name: build
on:
  workflow_dispatch:
  pull_request:
    branches: main

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1
      - name: Setup Java
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: oracle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0
      - name: Allow execution of gradle
        run: chmod +x ./gradlew
      - name: Build all classes
        run: ./gradlew build compileDebugAndroidTestSources compileDebugUnitTestSources compileReleaseUnitTestSources -x test
  test:
    name: Run Unit Tests
    needs: build
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1
      - name: Setup Java
        uses: actions/setup-java@v3.13.0
        with:
          distribution: oracle
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0
      - name: Allow execution of gradle
        run: chmod +x ./gradlew
      - name: Run Unit Tests
        run: ./gradlew test --continue
      - name: Build Report Debug Tests
        if: success() || failure()
        uses: scacap/action-surefire-report@v1.7.2
        with: 
          report_paths: '**/build/test-results/testDebugUnitTest/TEST-*.xml'
      - name: Build Report Release Tests
        if: success() || failure()
        uses: scacap/action-surefire-report@v1.7.2
        with: 
          report_paths: '**/build/test-results/testReleaseUnitTest/TEST-*.xml'
  androidTest:
    name: Run AndroidTests
    needs: build
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1
      - name: Setup Java
        uses: actions/setup-java@v3.13.0
        with:
          distribution: oracle
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0
      - name: Allow execution of gradle
        run: chmod +x ./gradlew
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedCheck
      - name: Build Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1.7.2
        with: 
          report_paths: '**/build/outputs/androidTest-results/connected/debug/TEST-*.xml'
      
